fix a typo
IBM/fhe-toolkit-macos pull request #51
Opened 2020-08-09 23:55 UTC by XuesongHu

phi(33) should be 20.
phi(33) = phi(3) * phi(11) = 2 * 10 = 20.

2020-08-10 15:43 UTC, faberga commented on fhe-toolkit-macos/SampleCode/CapitalDetailViewController.mm
> +//unsigned long m = 33;  // this will give 20 slots - runs faster
```suggestion
```

@XuesongHu your comment  regarding 20 slots and not 10 is correct.
That line was a leftover from when we changed the algebra to work with up to 48 slots to accommodate for up to 48 chars country/capital names. `m=33` will not work for this demo, so this line should be deleted.

Also, we changed slightly the organization of the directories which will cause merge conflicts. Can you rebase your fork , please?

Thanks

2020-08-10 15:44 UTC, faberga requested changes
@XuesongHu please see my comments above.

2020-08-13 03:19 UTC, XuesongHu commented
@faberga Per your comment, removed the unused comment line.

2020-08-13 12:34 UTC, faberga approved these changes
Approved as changes requested were completed.

2020-08-13 12:37 UTC, merged